import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout component for the application.
 *
 * Fetches the current authentication session on the server, provides it to
 * NextAuth's SessionProvider, and wraps the app's pages in the global HTML/body
 * shell with configured fonts and a responsive flex layout.
 *
 * This is an async server component — session retrieval via `auth()` is awaited
 * before rendering.
 *
 * @param children - The page content rendered inside the layout.
 * @returns The root JSX element tree for the application.
 */
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth()

  return (
    <SessionProvider session={session}>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
            <div className="flex flex-col min-h-screen">
             
    <div className="flex-1">
{children}
    </div>
            </div>
        
      </body>
    </html>
    </SessionProvider>
  );
}
